language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - nightly
  - hhvm

before_script:
- pear install --alldeps pear/PHP_CodeSniffer
- phpenv rehash

script:
- phpunit -c ./phpunit.xml
- phpcs --extensions=php -p --standard=PSR2 ./
